/* Generated by tools/sheet2neo.py - do not edit. */
#ifndef HERO_H
#define HERO_H

#define HERO_TILES_W 6
#define HERO_TILES_H 6
#define HERO_SHEET_W 48
#define HERO_TILE_COUNT 1152

#define HERO_WALK_FRAMES 8
#define HERO_WALK_ROW 0
#define HERO_ATTACK_FRAMES 8
#define HERO_ATTACK_ROW 6
#define HERO_JUMP_FRAMES 4
#define HERO_JUMP_ROW 12
#define HERO_CROUCH_FRAMES 2
#define HERO_CROUCH_ROW 18

/* 16 colours, index 0 transparent. */
static const u16 hero_palette[16] = {
    0x8000, 0xeb99, 0x4779, 0xc767,
    0x7557, 0x2645, 0x6446, 0x8445,
    0x6423, 0x1333, 0xf223, 0x0223,
    0x4112, 0x4000, 0x9000, 0x8000,
};

#endif
