/* Generated by tools/make_stage.py - do not edit. */
#ifndef STAGE_H
#define STAGE_H

#define STAGE_TILES_W 20
#define STAGE_TILES_H 14
#define STAGE_GROUND_Y 184

/* 16 colours, index 0 transparent. */
static const u16 stage_palette[16] = {
    0x8000, 0x9112, 0x7113, 0x2325,
    0xd446, 0x2edc, 0x7001, 0xe113,
    0x3112, 0xa211, 0x3321, 0xf432,
    0xa643, 0x3100, 0x4232, 0x2864,
};

#endif
