#!/usr/bin/env python3
"""Turn a region of a sprite sheet into a Neo Geo sprite tile sheet.

The Neo Geo draws sprites from 16x16 tiles, 4 bits per pixel, so a sprite may
use at most 16 colours and colour 0 is always transparent. Source art is
normally neither 16-colour nor a multiple of 16 pixels, so this does the
conversion:

  * cuts the region into N frames of equal width
  * finds one bounding box that fits every frame, so the animation does not
    jitter as frames change
  * pads that box out to whole tiles, keeping the feet on the bottom edge
  * quantises to 15 colours plus transparent, snapped to the Neo Geo's 5 bits
    per channel so the result matches what the hardware can actually show
  * writes a GIF laid out for ngdevkit's tiletool

Tiles are numbered left to right, then top to bottom, so with F frames of
W tiles across and H down, the tile at (column c, row r) of frame f is:

    base + r * (F * W) + f * W + c
"""

import argparse
from PIL import Image


def snap_to_neogeo(rgb):
    """Round a colour to what the Neo Geo can display.

    Each channel is 5 bits: 4 bits of its own plus one bit shared with the
    other channels. Rounding to 5 bits is a close enough approximation for
    choosing a palette.
    """
    return tuple((c >> 3) * 255 // 31 for c in rgb)


def common_bbox(frames):
    """One bounding box covering the visible pixels of every frame."""
    boxes = [f.getbbox() for f in frames]
    boxes = [b for b in boxes if b]
    if not boxes:
        raise SystemExit("error: every frame is empty")
    return (
        min(b[0] for b in boxes),
        min(b[1] for b in boxes),
        max(b[2] for b in boxes),
        max(b[3] for b in boxes),
    )


def to_color_word(r, g, b):
    """Pack an RGB colour into a Neo Geo palette word.

    Bit 15 is a "dark" bit shared by all three channels and is stored
    inverted; bits 14-12 hold each channel's low bit; bits 11-0 hold four
    bits each of red, green and blue.
    """
    r5, g5, b5 = r >> 3, g >> 3, b >> 3
    # The shared low bit is the best fit for the three channels' low bits.
    dark = 1 if (r5 & 1) + (g5 & 1) + (b5 & 1) >= 2 else 0
    word = (0 if dark else 1) << 15
    word |= ((r5 >> 1) & 1) << 14
    word |= ((g5 >> 1) & 1) << 13
    word |= ((b5 >> 1) & 1) << 12
    word |= ((r5 >> 1) & 0xF) << 8
    word |= ((g5 >> 1) & 0xF) << 4
    word |= (b5 >> 1) & 0xF
    return word


def write_header(args, palette, tw, th):
    name = args.name
    guard = f"{name.upper()}_H"
    words = []
    for i in range(16):
        r, g, b = palette[i * 3: i * 3 + 3]
        # Colour 0 is transparent; the hardware ignores its value.
        words.append(0x8000 if i == 0 else to_color_word(r, g, b))

    with open(args.header, "w") as f:
        f.write(f"/* Generated by tools/sheet2neo.py - do not edit. */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(f"#define {name.upper()}_FRAMES {args.frames}\n")
        f.write(f"#define {name.upper()}_TILES_W {tw}\n")
        f.write(f"#define {name.upper()}_TILES_H {th}\n")
        f.write(f"#define {name.upper()}_SHEET_W {tw * args.frames}\n\n")
        f.write(f"/* 16 colours, index 0 transparent. */\n")
        f.write(f"static const u16 {name}_palette[16] = {{\n")
        for i in range(0, 16, 4):
            row = ", ".join(f"0x{w:04x}" for w in words[i:i + 4])
            f.write(f"    {row},\n")
        f.write("};\n\n")
        f.write(f"#endif\n")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("sheet", help="source PNG")
    p.add_argument("-o", "--output", required=True, help="GIF to write")
    p.add_argument("--region", required=True, metavar="X,Y,W,H",
                   help="area of the sheet holding the animation")
    p.add_argument("--frames", type=int, required=True,
                   help="number of equal-width frames in that area")
    p.add_argument("--colors", type=int, default=15,
                   help="colours to use besides transparent (max 15)")
    p.add_argument("--flip", action="store_true",
                   help="mirror horizontally (the hardware can also do this "
                        "for free with the H-flip attribute)")
    p.add_argument("--header", metavar="FILE.h",
                   help="also write the palette and tile geometry as C")
    p.add_argument("--name", default="sprite",
                   help="identifier prefix used in the header")
    args = p.parse_args()

    if not 1 <= args.colors <= 15:
        raise SystemExit("error: --colors must be between 1 and 15")

    x, y, w, h = (int(v) for v in args.region.split(","))
    sheet = Image.open(args.sheet).convert("RGBA").crop((x, y, x + w, y + h))

    fw = w // args.frames
    frames = [sheet.crop((i * fw, 0, (i + 1) * fw, h)) for i in range(args.frames)]
    if args.flip:
        frames = [f.transpose(Image.FLIP_LEFT_RIGHT) for f in frames]

    left, top, right, bottom = common_bbox(frames)
    bw, bh = right - left, bottom - top

    # Pad out to whole tiles. Extra width is shared evenly so the sprite stays
    # centred; extra height goes on top so the feet stay on the bottom edge,
    # which is what a walk cycle needs to look planted.
    tw = (bw + 15) // 16
    th = (bh + 15) // 16
    pad_x = (tw * 16 - bw) // 2
    pad_y = th * 16 - bh

    out = Image.new("RGBA", (tw * 16 * args.frames, th * 16), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        cell = Image.new("RGBA", (tw * 16, th * 16), (0, 0, 0, 0))
        cell.paste(f.crop((left, top, right, bottom)), (pad_x, pad_y))
        out.paste(cell, (i * tw * 16, 0))

    # Snap every visible pixel to the hardware's colour space, then quantise.
    px = out.load()
    for py in range(out.height):
        for pxx in range(out.width):
            r, g, b, a = px[pxx, py]
            if a > 127:
                px[pxx, py] = snap_to_neogeo((r, g, b)) + (255,)
            else:
                px[pxx, py] = (0, 0, 0, 0)

    opaque = out.convert("RGB")
    quant = opaque.quantize(colors=args.colors, method=Image.MEDIANCUT)
    src_pal = quant.getpalette()[: args.colors * 3]

    # Shift every colour up by one so index 0 can mean transparent.
    indexed = Image.new("P", out.size, 0)
    indexed.putpalette([0, 0, 0] + src_pal + [0, 0, 0] * (15 - args.colors))
    qpx, opx, ipx = quant.load(), out.load(), indexed.load()
    for py in range(out.height):
        for pxx in range(out.width):
            ipx[pxx, py] = 0 if opx[pxx, py][3] < 128 else qpx[pxx, py] + 1

    indexed.save(args.output, transparency=0)

    if args.header:
        write_header(args, indexed.getpalette(), tw, th)

    print(f"{args.output}: {args.frames} frames of {tw}x{th} tiles "
          f"({tw * 16}x{th * 16} px), {args.colors} colours + transparent")
    print(f"sheet is {tw * args.frames} tiles wide, {th} tall "
          f"= {tw * args.frames * th} tiles total")
    print(f"tile(frame f, col c, row r) = base + r*{tw * args.frames} + f*{tw} + c")


if __name__ == "__main__":
    main()
