;;; Sound commands for the Z80.
;;;
;;; The 68000 cannot touch the sound chip: it writes a single byte to
;;; REG_SOUND and that fires an NMI on the Z80, which looks the byte up in the
;;; table below and runs the matching routine. So every sound the game can
;;; make is one entry here, and the 68000 side is just a number.
;;;
;;; Commands 0 to 3 are reserved by nullsound. Ours start at 4 and must stay
;;; in step with the SND_* values in main.c.

        .include "helpers.inc"
        .area   CODE

cmd_jmptable::
        ;; reserved by the driver
        jp      snd_command_unused
        jp      snd_command_01_prepare_for_rom_switch
        jp      snd_command_unused
        jp      snd_command_03_reset_driver
        ;; ours
        jp      play_coin
        jp      play_jump
        jp      play_punch
        init_unused_cmd_jmptable


play_coin:
        ld      ix, #adpcm_a_coin
        call    snd_adpcm_a_play
        ret

play_jump:
        ld      ix, #adpcm_a_jump
        call    snd_adpcm_a_play
        ret

play_punch:
        ld      ix, #adpcm_a_punch
        call    snd_adpcm_a_play
        ret


;;; Where each sample sits in the sample ROM, generated by vromtool.
        .include "assets/samples.inc"

;;; One descriptor per sample: start and stop offset in the V ROM, which of
;;; the six ADPCM-A channels to use, and the volume with both speakers on.
;;;
;;; The three sounds are on separate channels so they can overlap - landing a
;;; punch while still in the air should not cut the jump short.

adpcm_a_coin:
        .db     COIN_START_LSB
        .db     COIN_START_MSB
        .db     COIN_STOP_LSB
        .db     COIN_STOP_MSB
        .db     0                       ; channel 1
        .db     0xdf                    ; left and right, full volume
        .db     1                       ; channel 1, as a bit

adpcm_a_jump:
        .db     JUMP_START_LSB
        .db     JUMP_START_MSB
        .db     JUMP_STOP_LSB
        .db     JUMP_STOP_MSB
        .db     1                       ; channel 2
        .db     0xdf
        .db     2

adpcm_a_punch:
        .db     PUNCH_START_LSB
        .db     PUNCH_START_MSB
        .db     PUNCH_STOP_LSB
        .db     PUNCH_STOP_MSB
        .db     2                       ; channel 3
        .db     0xdf
        .db     4
